In [29]:
import numpy as np
import math

def Strassen(matriz_1,matriz_2): #Algoritmo de Strassen para 
    if (matriz_1.shape[0] != 2) or (matriz_1.shape[1] != 2) or (matriz_2.shape[0] != 2) or (matriz_2.shape[1] != 2):
        print("As matrizes devem ser do tipo 2x2")
        return None
    
    M1 = (matriz_1[0,0] + matriz_1[1,1]) * (matriz_2[0,0] + matriz_2[1,1])
    M2 = (matriz_1[1,0] + matriz_1[1,1]) * matriz_2[0,0]
    M3 = matriz_1[0,0] * (matriz_2[0,1] - matriz_2[1,1])
    M4 = matriz_1[1,1] * (matriz_2[1,0] - matriz_2[0,0])
    M5 = (matriz_1[0,0] + matriz_1 [0,1]) * matriz_2[1,1]
    M6 = (matriz_1[1,0] - matriz_1[0,0]) * (matriz_2[0,0] + matriz_2[0,1])
    M7 = (matriz_1[0,1] - matriz_1[1,1]) * (matriz_2[1,0] + matriz_2[1,1])
    
    Resultado = np.zeros([2,2])
    Resultado[0,0] = M1 + M4 - M5 + M7
    Resultado[0,1] = M3 + M5
    Resultado[1,0] = M2 + M4
    Resultado[1,1] = M1 - M2 + M3 + M6
    
    return Resultado

A = np.ones([6,3])
B = np.ones([3,6])
C = np.zeros([A.shape[0],B.shape[1]]) #Guarda o tamanho original da matriz multiplicada

#Checagem das condições pré-estabelecidas
if (len(A.shape) != 2) or (len(B.shape) != 2):
    print("Erro: As matrizes devem ser bidimensionais")
    
if (A.shape != B.shape):
    print("Erro: As matrizes devem possuir mesmas dimensões")

if (A.shape[1] != B.shape[0]):
    print("Erro: Não é possível realizar a multiplicação C = A * B com as matrizes fornecidas")
    
if ((A.shape[0] - A.shape[1]) != 0) or ((B.shape[0] - B.shape[1]) != 0):
    print("Erro: As mastrizes devem ser ambas quadradas")

if (math.ceil(math.log2(A.shape[0]) != math.floor(math.log2(A.shape[0])))) or (math.ceil(math.log2(A.shape[1]) != math.floor(math.log2(A.shape[1])))):
    print("A matriz A será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n")
    linhas = 2**math.ceil(math.log2(A.shape[0])) - A.shape[0] #Calcula quantas linhas faltam para um quadrado de dois
    colunas = 2**math.ceil(math.log2(A.shape[1])) - A.shape[1] #Calcula quantas colunas faltam para um quadrado de dois
    if linhas > colunas:
        matriz_auxiliar = np.zeros([linhas,A.shape[1]])
        A = np.vstack((A,matriz_auxiliar))
        matriz_auxiliar = np.zeros([A.shape[0],A.shape[0]-A.shape[1]])
        A = np.hstack((A,matriz_auxiliar))
        
    elif colunas >= linhas:
        matriz_auxiliar = np.zeros([A.shape[0],colunas])
        A = np.hstack((A,matriz_auxiliar))
        matriz_auxiliar = np.zeros([A.shape[1]-A.shape[0],A.shape[1]])
        A = np.vstack((A,matriz_auxiliar))
        
if (math.ceil(math.log2(B.shape[0]) != math.floor(math.log2(B.shape[0])))) or (math.ceil(math.log2(B.shape[1]) != math.floor(math.log2(B.shape[1])))):
    print("A matriz B será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n")
    linhas = 2**math.ceil(math.log2(B.shape[0])) - B.shape[0] #Calcula quantas linhas faltam para um quadrado de dois
    colunas = 2**math.ceil(math.log2(B.shape[1])) - B.shape[1] #Calcula quantas colunas faltam para um quadrado de dois
    if linhas > colunas:
        matriz_auxiliar = np.zeros([linhas,B.shape[1]])
        B = np.vstack((B,matriz_auxiliar))
        matriz_auxiliar = np.zeros([B.shape[0],B.shape[0]-B.shape[1]])
        B = np.hstack((B,matriz_auxiliar))
        
    elif colunas >= linhas:
        matriz_auxiliar = np.zeros([B.shape[0],colunas])
        B = np.hstack((B,matriz_auxiliar))
        matriz_auxiliar = np.zeros([B.shape[1]-B.shape[0],B.shape[1]])
        B = np.vstack((B,matriz_auxiliar))

#Separação das matrizes em submatrizes 2x2
a_aux = []
b_aux = []
a=[]
b=[]
for i in range(0,A.shape[0],2):
    for j in range(0,A.shape[1],2):
        a_aux.append(A[i:i+2,j:j+2])
        b_aux.append(B[i:i+2,j:j+2])
    a.append(a_aux)
    b.append(b_aux)
    a_aux = []
    b_aux = []

# Multiplicação das matrizes
c = []
for i in range(len(a)):
    c.append([])
    for j in range(len(a)):
        c[i].append(Strassen(a[i][j],b[j][i]))

C1 = np.array(c)
C = C1[0:C.shape[0],0:C.shape[1]]
print(C1)

#Por algum motivo, o algoritmo de strassen está funcionando mal

Erro: As matrizes devem possuir mesmas dimensões
Erro: As mastrizes devem ser ambas quadradas
A matriz A será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n
A matriz B será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n
[[[[2. 2.]
   [2. 2.]]

  [[1. 1.]
   [1. 1.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[2. 2.]
   [2. 2.]]

  [[1. 1.]
   [1. 1.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[2. 2.]
   [2. 2.]]

  [[1. 1.]
   [1. 1.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [21]:
C = Strassen(b[0][0],a[0][0])
C1 = np.matmul(A,B)
print(C1)

48.0 6.0 -12.0 12.0 70.0 -8.0 72.0
[[18. 14.]
 [62. 66.]]


In [24]:
print(C.shape)

(4, 4, 2, 2)


In [26]:
S = np.ones([6,3])
R = np.ones([3,6])
print(np.matmul(S,R))

[[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]
