In [44]:
import numpy as np
import math

def multi_strassen(A,B,check_dim = True, check_ig = True, check_quad = True, check_pot = True):
    
    def Strassen(matriz_1,matriz_2): # Função do algoritmo de Strassen para multiplicação de matrizes do tipo 2x2
        if (matriz_1.shape[0] != 2) or (matriz_1.shape[1] != 2) or (matriz_2.shape[0] != 2) or (matriz_2.shape[1] != 2):
            print("As matrizes devem ser do tipo 2x2")
            return None

        M1 = (matriz_1[0,0] + matriz_1[1,1]) * (matriz_2[0,0] + matriz_2[1,1])
        M2 = (matriz_1[1,0] + matriz_1[1,1]) * matriz_2[0,0]
        M3 = matriz_1[0,0] * (matriz_2[0,1] - matriz_2[1,1])
        M4 = matriz_1[1,1] * (matriz_2[1,0] - matriz_2[0,0])
        M5 = (matriz_1[0,0] + matriz_1 [0,1]) * matriz_2[1,1]
        M6 = (matriz_1[1,0] - matriz_1[0,0]) * (matriz_2[0,0] + matriz_2[0,1])
        M7 = (matriz_1[0,1] - matriz_1[1,1]) * (matriz_2[1,0] + matriz_2[1,1])

        Resultado = np.zeros([2,2])
        Resultado[0,0] = M1 + M4 - M5 + M7
        Resultado[0,1] = M3 + M5
        Resultado[1,0] = M2 + M4
        Resultado[1,1] = M1 - M2 + M3 + M6

        return Resultado
    
    inicio = datetime.datetime.now()
    C = np.zeros([A.shape[0],B.shape[1]]) #Guarda o tamanho original da matriz multiplicada

    #Parte 1: Checagem das condições pré-estabelecidas
    if (A.shape[1] != B.shape[0]):
        print("Erro: Não é possível realizar a multiplicação C = A * B com as matrizes fornecidas")

    if check_dim:
        
        if (len(A.shape) != 2) or (len(B.shape) != 2): #Checa a dimensão da matriz
            print("Erro: As matrizes devem ser bidimensionais")
            return None

    if check_ig:
        
        if (A.shape != B.shape): #Checa se as matrizes possuem mesma dimensão
            print("Erro: As matrizes devem possuir mesmas dimensões")
            return None
       
    if check_quad:
        
        if ((A.shape[0] - A.shape[1]) != 0) or ((B.shape[0] - B.shape[1]) != 0):
            print("Erro: As matrizes devem ser ambas quadradas")
            return None

    if check_pot:
        
        if (math.ceil(math.log2(A.shape[0]) != math.floor(math.log2(A.shape[0])))) or (math.ceil(math.log2(A.shape[1]) != math.floor(math.log2(A.shape[1])))):
            print("A matriz A será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n")
            linhas = 2**math.ceil(math.log2(A.shape[0])) - A.shape[0] #Calcula quantas linhas faltam para um quadrado de dois
            colunas = 2**math.ceil(math.log2(A.shape[1])) - A.shape[1] #Calcula quantas colunas faltam para um quadrado de dois
            if linhas > colunas:
                matriz_auxiliar = np.zeros([linhas,A.shape[1]])
                A = np.vstack((A,matriz_auxiliar))
                matriz_auxiliar = np.zeros([A.shape[0],A.shape[0]-A.shape[1]])
                A = np.hstack((A,matriz_auxiliar))

            elif colunas >= linhas:
                matriz_auxiliar = np.zeros([A.shape[0],colunas])
                A = np.hstack((A,matriz_auxiliar))
                matriz_auxiliar = np.zeros([A.shape[1]-A.shape[0],A.shape[1]])
                A = np.vstack((A,matriz_auxiliar))

        if (math.ceil(math.log2(B.shape[0]) != math.floor(math.log2(B.shape[0])))) or (math.ceil(math.log2(B.shape[1]) != math.floor(math.log2(B.shape[1])))):
            print("A matriz B será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n")
            linhas = 2**math.ceil(math.log2(B.shape[0])) - B.shape[0] #Calcula quantas linhas faltam para um quadrado de dois
            colunas = 2**math.ceil(math.log2(B.shape[1])) - B.shape[1] #Calcula quantas colunas faltam para um quadrado de dois
            if linhas > colunas:
                matriz_auxiliar = np.zeros([linhas,B.shape[1]])
                B = np.vstack((B,matriz_auxiliar))
                matriz_auxiliar = np.zeros([B.shape[0],B.shape[0]-B.shape[1]])
                B = np.hstack((B,matriz_auxiliar))

            elif colunas >= linhas:
                matriz_auxiliar = np.zeros([B.shape[0],colunas])
                B = np.hstack((B,matriz_auxiliar))
                matriz_auxiliar = np.zeros([B.shape[1]-B.shape[0],B.shape[1]])
                B = np.vstack((B,matriz_auxiliar))


    #Multiplicação de fato das matrizes
    
    D = np.zeros_like(A)
    for i in range(0,A.shape[0],2):
        for j in range(0,B.shape[1],2):
            soma = 0
            for k in range(0,A.shape[1],2):
                soma = soma + Strassen(A[i:i+2,k:k+2],B[k:k+2,j:j+2])
            D[i:i+2,j:j+2] = soma
    C = D[0:C.shape[0],0:C.shape[1]]
    print (C)
    fim = datetime.datetime.now()
    print("Tempo de execução = ", fim - inicio)
    return C


In [40]:
S = np.random.randn(6,3)
R = np.random.randn(3,6)
print(S)
print('')
print('')
print(R)
print('')
print('')
print(np.matmul(S,R))

[[ 0.72986227  2.13382979  0.78212883]
 [-0.57027204  0.07582152 -0.05656516]
 [ 0.38243788  2.0751144   0.31587645]
 [ 0.81782401  1.01833361 -0.74341452]
 [ 1.2195497  -1.17691075  0.70893001]
 [-0.38040841  0.66484304  0.61611711]]


[[ 1.59124356 -0.43297243  1.54981836 -0.62379499 -0.6455533   0.73140462]
 [ 0.49535293 -0.61812787 -0.33925219 -1.00519079  0.18298254 -0.96125102]
 [-1.06316425 -0.26301374  0.65767556 -0.16350672 -2.00616619  0.03425339]]


[[ 1.38685606 -1.84070054  0.92163453 -2.72807379 -1.64979183 -1.49053088]
 [-0.80974525  0.21492209 -0.94674222  0.28876653  0.49549412 -0.49192067]
 [ 1.30063727 -1.53135096  0.09646636 -2.37609664 -0.50087499 -1.70416918]
 [ 2.59616348 -0.78802741  0.43308119 -1.41222082  1.14980135 -0.40617843]
 [ 0.60390536  0.0129916   2.75559601  0.30635603 -2.42486988  2.0475742 ]
 [-0.93102416 -0.40829893 -0.40990823 -0.53173652 -0.86880473 -0.89620942]]


In [41]:
multi_strassen(S,R,check_dim = False,check_ig = False,check_quad = False, check_pot = True)

A matriz A será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n
A matriz B será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n
[[ 1.38685606 -1.84070054  0.92163453 -2.72807379 -1.64979183 -1.49053088]
 [-0.80974525  0.21492209 -0.94674222  0.28876653  0.49549412 -0.49192067]
 [ 1.30063727 -1.53135096  0.09646636 -2.37609664 -0.50087499 -1.70416918]
 [ 2.59616348 -0.78802741  0.43308119 -1.41222082  1.14980135 -0.40617843]
 [ 0.60390536  0.0129916   2.75559601  0.30635603 -2.42486988  2.0475742 ]
 [-0.93102416 -0.40829893 -0.40990823 -0.53173652 -0.86880473 -0.89620942]]


array([[ 1.38685606, -1.84070054,  0.92163453, -2.72807379, -1.64979183,
        -1.49053088],
       [-0.80974525,  0.21492209, -0.94674222,  0.28876653,  0.49549412,
        -0.49192067],
       [ 1.30063727, -1.53135096,  0.09646636, -2.37609664, -0.50087499,
        -1.70416918],
       [ 2.59616348, -0.78802741,  0.43308119, -1.41222082,  1.14980135,
        -0.40617843],
       [ 0.60390536,  0.0129916 ,  2.75559601,  0.30635603, -2.42486988,
         2.0475742 ],
       [-0.93102416, -0.40829893, -0.40990823, -0.53173652, -0.86880473,
        -0.89620942]])

In [ ]:
#Código péssimo, desconsiderar

#Separação das matrizes em submatrizes 2x2
a_aux = []
b_aux = []
a=[]
b=[]
for i in range(0,A.shape[0],2):
    for j in range(0,A.shape[1],2):
        a_aux.append(A[i:i+2,j:j+2])
        b_aux.append(B[i:i+2,j:j+2])
    a.append(a_aux)
    b.append(b_aux)
    a_aux = []
    b_aux = []

# Multiplicação das matrizes
c = []
for i in range(len(a)):
    c.append([])
    print(c)
    c1 = np.zeros((2,2))
    for j in range(len(a)):
        c1 = c1 + (Strassen(a[i][j],b[j][i]))
    c[i].append(c1)

C1 = np.array(c) #Não tem como formatar automaticamente?
c = C1[0][0]
for i in range(1,C1.shape[0]):
    c = np.hstack((c,C1[i][i]))

D = c
for i in range(1,C1.shape[0]):
    c = C1[i][0]
    for j in range(1,C1.shape[1]):
        c = np.hstack((c,C1[i][j]))
    D = np.vstack((D,c))
    
    
C = D[0:C.shape[0],0:C.shape[1]]
print(C)

#Por algum motivo, o algoritmo de strassen está funcionando mal

In [45]:
import datetime

multi_strassen(S,R,check_dim = False,check_ig = False,check_quad = False, check_pot = True)



A matriz A será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n
A matriz B será modificada, acrescentando-se zeros para que torne-se uma matriz do tipo 2^n x 2^n
[[ 1.38685606 -1.84070054  0.92163453 -2.72807379 -1.64979183 -1.49053088]
 [-0.80974525  0.21492209 -0.94674222  0.28876653  0.49549412 -0.49192067]
 [ 1.30063727 -1.53135096  0.09646636 -2.37609664 -0.50087499 -1.70416918]
 [ 2.59616348 -0.78802741  0.43308119 -1.41222082  1.14980135 -0.40617843]
 [ 0.60390536  0.0129916   2.75559601  0.30635603 -2.42486988  2.0475742 ]
 [-0.93102416 -0.40829893 -0.40990823 -0.53173652 -0.86880473 -0.89620942]]
Tempo de execução =  0:00:00.002929


array([[ 1.38685606, -1.84070054,  0.92163453, -2.72807379, -1.64979183,
        -1.49053088],
       [-0.80974525,  0.21492209, -0.94674222,  0.28876653,  0.49549412,
        -0.49192067],
       [ 1.30063727, -1.53135096,  0.09646636, -2.37609664, -0.50087499,
        -1.70416918],
       [ 2.59616348, -0.78802741,  0.43308119, -1.41222082,  1.14980135,
        -0.40617843],
       [ 0.60390536,  0.0129916 ,  2.75559601,  0.30635603, -2.42486988,
         2.0475742 ],
       [-0.93102416, -0.40829893, -0.40990823, -0.53173652, -0.86880473,
        -0.89620942]])